# PyTorch Cross-Entropy Loss

In [1]:
import torch
import torch.nn as nn

In [5]:
# Define Some Input Data
# Define 3 Samples and 4 Classes
preds = torch.randn(3, 4)

# Define Target Class Indices
labels = torch.LongTensor([0, 1, 2])

print(f'Input data: \n{preds}')
print(f'\nLabels:\n{labels}')

Input data: 
tensor([[ 0.3703, -0.1607, -0.7473, -2.2135],
        [ 0.6929, -0.2042, -0.7660, -0.3613],
        [-0.3363,  0.6417,  0.3103,  0.3132]])

tensor([0, 1, 2])


In [7]:
# Define Loss Function
loss_func = nn.CrossEntropyLoss()
loss = loss_func(preds, labels)

print(f'Loss: {loss}')

Loss: 1.2129982709884644


In [ ]:
# Input data: 
# tensor([[ 0.3703, -0.1607, -0.7473, -2.2135],
#         [ 0.6929, -0.2042, -0.7660, -0.3613],
#         [-0.3363,  0.6417,  0.3103,  0.3132]])

# tensor([0, 1, 2])