# PyTorch Tensors

In [1]:
import torch
import numpy as np

## Creating Tensors

In [2]:
# Creating a Tensor From Scratch
data = [[1, 2], [3, 4], [5, 6]]
tensor_data = torch.tensor(data)

print(tensor_data)

# Returns:
# tensor([[1, 2],
#         [3, 4],
#         [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [3]:
# Checking the Type of Tensors
print(type(tensor_data))

# Returns: <class 'torch.Tensor'>

<class 'torch.Tensor'>


In [4]:
# Creating a Tensor From NumPy
np_array = np.array(data)
tensor_np = torch.from_numpy(np_array)

print(tensor_np)

# Returns:
# tensor([[1, 2],
#         [3, 4],
#         [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Creating Tensors with Random and Constant Values

In [5]:
# Creating Tensors of 1s
ones = torch.ones(size=(3,2))
print(ones)

# Returns:
# tensor([[1., 1.],
#         [1., 1.],
#         [1., 1.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [6]:
# Creating Tensors of 0s
zeros = torch.zeros(size=(3,2))
print(zeros)

# Returns:
# tensor([[0., 0.],
#         [0., 0.],
#         [0., 0.]])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
# Creating Tensors with Fill Values
filled = torch.full(size=(3, 2), fill_value=2)
print(filled)

# Returns:
# tensor([[2, 2],
#         [2, 2],
#         [2, 2]])

tensor([[2, 2],
        [2, 2],
        [2, 2]])


In [18]:
# Creating Random Tensors
randoms = torch.rand(size=(3,2))
print(randoms)

# Returns:
# tensor([[0.5215, 0.2354],
#         [0.2960, 0.6190],
#         [0.1766, 0.8673]])

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])


In [20]:
# Adding Reproducibility to Our Tensors
torch.manual_seed(42)
randoms = torch.rand(size=(3,2))
print(randoms)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])


## Working with Different Data Types

In [18]:
# Checking the Data Type of a Tensor
zeros = torch.zeros((3,2))
print(zeros.dtype)

# Returns: torch.float32

torch.float32


In [20]:
# Changing a Tensor to a Different Data Type
zeros = torch.zeros((3, 2), dtype=torch.int)
print(zeros)

# Returns:
# tensor([[0, 0],
#         [0, 0],
#         [0, 0]], dtype=torch.int32)

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [21]:
# Converting an Existing Tensor to Another Data Type
int_tensor = torch.tensor([1, 2, 3, 4, 5])
float_tensor = int_tensor.to(torch.float32)

print(f'Int tensor:\n{int_tensor}')
print(f'\nFloat tensor:\n{float_tensor}')

# Returns:
# Int tensor:
# tensor([1, 2, 3, 4, 5])

# Float tensor:
# tensor([1., 2., 3., 4., 5.])

Int tensor:
tensor([1, 2, 3, 4, 5])

Float tensor:
tensor([1., 2., 3., 4., 5.])


## Creating Like-Sized Tensors

In [22]:
# Creating Like-sized Tensors
data = [[1, 2], [3, 4], [5, 6]]
tensor_data = torch.tensor(data)

zeros_like = torch.zeros_like(tensor_data)
ones_like = torch.ones_like(tensor_data)
random_like = torch.rand_like(tensor_data, dtype=torch.float)

print(f'Zeros Like:\n{zeros_like}')
print(f'\nOnes Like:\n{ones_like}')
print(f'\nRandom Like:\n{random_like}')

# Returns:
# Zeros Like: 
# tensor([[0, 0],
#         [0, 0],
#         [0, 0]])

# Ones Like: 
# tensor([[1, 1],
#         [1, 1],
#         [1, 1]])

# Random Like: 
# tensor([[0.9938, 0.3513],
#         [0.6042, 0.2700],
#         [0.7633, 0.9896]])

Zeros Like:
tensor([[0, 0],
        [0, 0],
        [0, 0]])

Ones Like:
tensor([[1, 1],
        [1, 1],
        [1, 1]])

Random Like:
tensor([[0.9350, 0.4455],
        [0.5805, 0.0069],
        [0.3253, 0.1886]])


## Tensor Attributes

In [23]:
# Understanding Different Tensor Attributes
data = torch.tensor([[1, 2], [3, 4]])

print(f"Shape of tensor: {data.shape}")
print(f"Datatype of tensor: {data.dtype}")
print(f"Device tensor is stored on: {data.device}")

# Returns:
# Shape of tensor: torch.Size([2, 2])
# Datatype of tensor: torch.int64
# Device tensor is stored on: cpu

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


## Tensor Operations

In [40]:
# Slicing a Tensor
data = torch.ones((2, 3))
print(f'Indexing the first row:\n{data[0]}')
print(f'Indexing the first column:\n{data[:, 0]}')

# Returns:
# Indexing the first row:
# tensor([1., 1., 1.])
# Indexing the first column:
# tensor([1., 1.])

Indexing the first row:
tensor([1., 1., 1.])
Indexing the first column:
tensor([1., 1.])


In [51]:
# Indexing a Tensor
data = torch.ones((2, 3))
print(data[0][0])

# Returns: tensor(1.)

tensor(1.)


In [41]:
# Setting Values Using Slicing
data = torch.ones((2, 3))
data[:, 0] = 0
print(data)

# Returns:
# tensor([[0., 1., 1.],
#         [0., 1., 1.]])

tensor([[0., 1., 1.],
        [0., 1., 1.]])


In [52]:
# Adding Tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.ones((2, 2))
added = tensor1.add(tensor2)
# added = tensor1 + tensor2
print(added)

# Returns:
# tensor([[2., 3.],
#         [4., 5.]])

tensor([[2., 3.],
        [4., 5.]])


In [5]:
# Adding a Scalar to a Tensor
tensor = torch.ones((2,2))
tensor = tensor.add(1)
# tensor = tensor + 1
print(tensor)

# Returns:
# tensor([[2., 2.],
#         [2., 2.]])

tensor([[2., 2.],
        [2., 2.]])

In [47]:
# Multipling Tensors
tensor = torch.rand((2, 3))
multiplied = tensor.multiply(tensor)
# multiplied = tensor * tensor
print(multiplied)

# Returns: 
# tensor([[0.2825, 0.0252, 0.4279],
#         [0.1075, 0.4267, 0.1567]])

tensor([[0.2825, 0.0252, 0.4279],
        [0.1075, 0.4267, 0.1567]])


In [50]:
# In Place Operations
ones = torch.ones((2, 3))
print(f'Original tensor:\n{ones}')
ones.add_(3)
print(f'\nTensor with inplace operations:\n{ones}')

# Returns:
# Original tensor:
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

# Tensor with inplace operations:
# tensor([[4., 4., 4.],
#         [4., 4., 4.]])

Original tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor with inplace operations:
tensor([[4., 4., 4.],
        [4., 4., 4.]])


## Manipulating Tensors

In [42]:
# Transposing a Tensor
data = torch.ones((2, 3))
transposed = data.T

print(f'Original tensor:\n{data}')
print(f'\nTransposed tensor:\n{transposed}')

# Returns:
# Original tensor:
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])
#
# Transposed tensor:
# tensor([[1., 1.],
#         [1., 1.],
#         [1., 1.]])

Original tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Transposed tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [57]:
# Reshaping a Tensor Using view
ones = torch.ones((3, 2))
one_dim = ones.view(6)

print(f'Original tensor:\n{ones}')
print(f'\nUpdated tensor:\n{one_dim}')

# Returns:
# Original tensor:
# tensor([[1., 1.],
#         [1., 1.],
#         [1., 1.]])

# Updated tensor:
# tensor([1., 1., 1., 1., 1., 1.])

Original tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Updated tensor:
tensor([1., 1., 1., 1., 1., 1.])


In [59]:
# Reshaping a Tensor Using view to Multiple Dimensions
ones = torch.ones((3, 2))
one_dim = ones.view(2, 3)

print(f'Original tensor:\n{ones}')
print(f'\nUpdated tensor:\n{one_dim}')

# Returns:
# Original tensor:
# tensor([[1., 1.],
#         [1., 1.],
#         [1., 1.]])

# Updated tensor:
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

Original tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Updated tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [58]:
# Reshaping a Tensor Using view Using Negative Values
ones = torch.ones((3, 2))
one_dim = ones.view(-1, 3)

print(f'Original tensor:\n{ones}')
print(f'\nUpdated tensor:\n{one_dim}')

# Returns:
# Original tensor:
# tensor([[1., 1.],
#         [1., 1.],
#         [1., 1.]])

# Updated tensor:
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

Original tensor:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Updated tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Converting Tensors to NumPy

In [60]:
# Converting a Tensor to a NumPy Array
tensor = torch.tensor([1, 2, 3, 4])
numpy_array = tensor.numpy()
print(numpy_array)

# Returns: [1 2 3 4]

[1 2 3 4]


## Working with Devices

In [62]:
# Creating a Device Variable
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [63]:
# Checking the Device of a Tensor
tensor = torch.tensor([1, 2, 3, 4])
print(tensor.device)

# Returns: cpu

cpu


In [ ]:
# Moving a Tensor to a Device
tensor = tensor.to(device)

In [ ]:
# Creating a Tensor with a Device
tensor = torch.tensor([1, 2, 3, 4], device=device)

## Tracking Gradients in PyTorch

In [65]:
# Adding Gradient Tracking
tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32, requires_grad=True)
print(tensor)

# Returns:
# tensor([1., 2., 3., 4.], requires_grad=True)

tensor([1., 2., 3., 4.], requires_grad=True)
